export enum NotificationStatus {
  NEW_SUBSCRIPTION = 'NEW_SUBSCRIPTION',
  NEW_CLIENT = 'NEW_CLIENT',
  NEW_CLIENTS = 'NEW_CLIENTS',
  HUB_INVITE = 'HUB_INVITE',
  PRODUCT_PURCHASE = 'PRODUCT_PURCHASE',
  PRODUCT_PURCHASES = 'PRODUCT_PURCHASES',
  INACTIVITY_ALERT = 'INACTIVITY_ALERT',
}
