export enum ProfileEvents {
  TITLE,
  ABOUT,
  PHOTO,
}

export enum ProductEvents {
  SWITCH_EVENT,
  SWITCH_VOD,
  ADDITIONAL_INFORMATION,
  VOD_TITLE,
  VOD_DESCRIPTION,
  VOD_FILE,
  VOD_THUMBNAIL,
  EVENT_TITLE,
  EVENT_DESCRIPTION,
  EVENT_IMAGE,
  EVENT_LINK,
  EVENT_DATE,
  EVENT_TIME,
  PRICE,
  CURRENCY,
  LANGUAGE,
}

export enum ShareEvents {
  EXPERT_PAGE,
  COPY_LINK,
  FURTHER_INFO,
}

export enum HomePageEvents {
  MY_EXPERT_PAGE,
  EXPECTED_EARNINGS_DASHBOARD,
  CLIENT_OVERVIEW_DASHBOARD,
  WEEKLY_ORDERS_DASHBOARD,
  FEATURES_HUB,
  FEATURES_EVENTS,
  FEATURE_ORDERS,
  FEATURE_CLIENTS,
  FEATURE_BILLING_ACCOUNT,
  FEATURE_VOD,
}

export enum SettingsPageEvents {
  MY_PROFILE,
  LEGAL,
  PAYMENTS,
  MEDIA_LIBRARY,
  NOTIFICATION,
}
